name: ci-appengine-php-update-workflow

on:
  schedule:
  # Run every day at 10AM.
  - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  update-php-versions:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Enable OIDC
    steps:
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: Get available PHP versions
      run: |
        # Get all supported PHP versions and pass the space-separated versions
        # string to the next step
        versions=$(gcloud functions runtimes list --format="value(NAME)" --project=gae-runtimes-private --region=us-west1 | grep ^php | tr '\n' ' ' | xargs)
        echo "::set-output name=versions::$versions"
      id: get_versions

    - name: Checkout appengine repo
      uses: actions/checkout@v2
      with:
        repository: GoogleCloudPlatform/appengine-php-sdk

    # Sign the commit.
    # https://www.chainguard.dev/unchained/keyless-git-commit-signing-with-gitsign-and-github-actions
    - uses: chainguard-dev/actions/setup-gitsign@main

    - name: Update PHP versions
      run: |
        readarray -d ' ' -t versions <<< "${{ steps.get_versions.outputs.versions }}"
        # Trim newline from last element
        versions[-1]=$(printf '%s' "${versions[-1]}")

        versions_str=""
        for version in "${versions[@]}"; do
          major=${version:3:1}
          minor=${version:4}
          versions_str+="'$major.$minor', "
        done
        # Remove the last comma and space
        versions_str=${versions_str%, *}

        # Only replace the first occurance
        sed -i "0,/^        php-versions: \[.*/s//        php-versions: \[$versions_str\]/" .github/workflows/ci.yaml
  
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.PAT }}
        commit-message: Update php-version matrix
        title: "[Automation] Update php-version matrix"
        body: |
          - php-version matrix updates

          Update the php-version matrix in the CI workflows to include the new supported runtimes.
 
          Auto-generated by ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        push-to-fork: chizhg/appengine-php-sdk
        branch: update-php-version-matrix
        signoff: true
        delete-branch: true
